[build]
  command = "npm run generate"

[context.production.environment]
NUXT_ENV_ACCESS_KEY_ID=AKIASLVDMQMBOCHEV25F
NUXT_ENV_SECRET_KEY_ID=5705hRFiP/hSAXaR1yAptjPQ0v/xBdAlVTca6t2g
NUXT_ENV_FROM_EMAIL_ADDRESS=admin@boyx@co.uk
NUXT_ENV_TO_EMAIL_ADDRESS=jackboyle35@gmail.com
NUXT_ENV_REGION=eu-north-1
